### ISSUE TITLE
School of CIT instead of department

### ISSUE THREAD

**Issue by emergenz** [TUM-Dev/tum-thesis-latex#13]

**Comment by CommanderStorm** [comment]
What exactly are you referring to?
This seems resolved, as the current codebase does not refer to departments but schools since https://github.com/TUM-Dev/tum-thesis-latex/pull/6 and https://github.com/TUM-Dev/tum-thesis-latex/pull/7
![image](https://github.com/TUM-Dev/tum-thesis-latex/assets/26258709/3b0cf0d1-6a4b-4f36-a02a-72ef9783b0ad)

**Comment by COM8** [comment]
Closing this one since no response and not enough information provided.

@emergenz feel free to reopen in case there is something needing to be fixed.

**Comment by emergenz** [comment]
It's still wrong in the build, that's why I opened the issue. Did not realize that it has already been corrected in the source.
