### ISSUE TITLE
What is the difference between build/main.pdf and build/fachschaft_print.pdf?

### ISSUE THREAD

**Issue by jalil-salame** [TUM-Dev/tum-thesis-latex#21]
From what I can tell, it tries to fix some issue with the `twoside` configuration of the thesis, but it is not documented in the README or the Makefile.

https://github.com/TUM-Dev/tum-thesis-latex/blob/c98745b81da2612e823644989de0bbe4f16f6509/Makefile#L12-L28

My guess is that line 23 removes pages 1 and 3 because they are blank?

If it is not using the `twoside` mode, then it just copies `main.pdf` to `fachschaft_print.pdf`.

**Comment by CommanderStorm** [comment]
The paragraph mentioned on https://github.com/TUM-Dev/tum-thesis-latex/pull/15 does not exist on the current website any more.

I have asked a friend at the student council if this is still necessary ^^

**Comment by jalil-salame** [comment]
It is still nice to remove the extra pages, but it is still a hack and should probably be removed if it is no longer necessary.

**Comment by CommanderStorm** [comment]
Mpic has asked us to leave this as an option as a backup.
The background is that with their current workflow, this page must not exist.

While they do have an option in their custom build printing software to remove this, they have not found a way of automating this.
If you choose duplex vs simplex depends on the amount of pages in your thesis as for one option half of the pages are empty. => inserting said empty page fucks with the layout somehow.

MPIC has looked into automating this process, but for the time being have not found a good solution that works with all the weirdnesses of PDF (did you know that PDF are apparently turning complete because of PostScript?)

**Comment by CommanderStorm** [comment]
Idk if we should document this if this is only a backup process..

**Comment by jalil-salame** [comment]
> MPIC has looked into automating this process, but for the time being have not found a good solution that works with all the weirdnesses of PDF (did you know that PDF are apparently turning complete because of PostScript?)

I knew PDFs were f-ed up, but I did not expect this...

My assumption is that most tools will not use the PDF's Turing complete features, but with how cursed LaTeX itself is I would not be surprised.

> Idk if we should document this if this is only a backup process..

I would err on the side of more documentation, a simple comment pointing to this issue should be enough:

```make
# Fix PDF for printing when using the twoside mode
# (see https://github.com/TUM-Dev/tum-thesis-latex/issues/21)
.PHONY: _fachschaft-print 
_fachschaft-print: 
    ...
```

**Comment by CommanderStorm** [comment]
> I can probably make a PR with that exact comment.

Yes, but said comment makes this appear to be a generally superior option (its not, its just different).

```
MPIC does not allow there to be the empty second page if using the twoside mode
see https://github.com/TUM-Dev/tum-thesis-latex/issues/21 for further context
```

**Comment by COM8** [comment]
Closing this one since it looks to be resolved.
